### ISSUE TITLE
zig build release issue:  Failed to find OpenSSL development headers

### ISSUE THREAD

**Issue by nathantippy-il** [cargo-lambda/cargo-lambda#708]
// After getting the error below I built a new Docker file trying to fix it

FROM ghcr.io/cargo-lambda/cargo-lambda:latest
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev

// Then built it and did my build --release  of my lambda project 

docker build -t custom-cargo-lambda .
docker run --rm -v $(pwd):/app -w /app custom-cargo-lambda cargo lambda build --release
 
/// here is a bit of the trace where the failure happens 
/// this is the same error with my Docker or using the the cargo-lambda Docker directly

  DEBUG = Some(false)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=In file included from build/expando.c:1:
  cargo:warning=In file included from /usr/include/openssl/opensslv.h:109:
  cargo:warning=/usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
  cargo:warning=   14 | #include <openssl/opensslconf.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.

  --- stderr
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.104/build/main.rs:264:13:

  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"/root/.cache/cargo-zigbuild/0.19.0/zigcc-x86_64-unknown-linux-gnu-7d27.sh\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"--target=x86_64-unknown-linux-gnu\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args zigcc-x86_64-unknown-linux-gnu-7d27.sh did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install pkg-config libssl-dev
      # On Arch Linux
      sudo pacman -S pkgconf openssl
      # On Fedora
      sudo dnf install pkgconf perl-FindBin perl-IPC-Cmd openssl-devel
      # On Alpine Linux
      apk add pkgconf openssl-dev

  See rust-openssl documentation for more information:

      https://docs.rs/openssl

**Comment by calavera** [comment]
Do you need OpenSSL specifically? or you're trying to use some kind of TLS connection? If it's the later, I'd recommend you to not use OpenSSL for AWS Lambda, because the Lambda sandbox won't probably have the same libraries that you're trying to link with. See this troubleshooting guide:

https://www.cargo-lambda.info/guide/cross-compiling.html#known-cross-compilation-issues

**Comment by calavera** [comment]
Since you're building your code inside a Docker container, you can also skip the cross-compilation linker adding `--compiler cargo` to the build subcommand. That should generate a linux binary since you're building on linux directly.

I'm going to close this ticket since this behavior is documented in the cross compilation guideline.
