### ISSUE TITLE
Deploy Indicates If a Build Needs to Be Done?

### ISSUE THREAD

**Issue by soisyourface** [cargo-lambda/cargo-lambda#743]
Cargo lambda is excellent!

I was "burned" by me being dumb the other day. Wasted more hours than I want to admit.
Basic story is that I was changing code and `cargo lambda deploy`ing but forgot that I have to `cargo lambda build` first and that `deploy` doesn't do that step.

Proposal is to add a message or something to the output of `deploy` that indicates that what is being deployed is not the same as what is in the code because you haven't done a `build`? Kind of like a "dirty" flag or something for releases and stuff.

This was an expensive lesson for me and would love to figure out a way to help folks in the future not make this same mistake.

**Comment by calavera** [comment]
Thanks for opening this issue. That's an interesting thought, but it sounds a little tricky to know what people expect and don't expect to deploy. 

Maybe some more information in each deploy would be enough, something like `Deploying binary AAA built 3 hours ago`. I've been thinking that the current progress formatting is not good enough because it removes messages, and a log closer to how Cargo prints information during build might be more useful in general.

**Comment by calavera** [comment]
I've made some improvements to the deploy output. Starting in the next release, it will tell you when the binary was compiled last. Here's an example of what it looks like:

![image](https://github.com/user-attachments/assets/b5a1af78-5d72-4993-ae70-727bcdadcb45)

**Comment by calavera** [comment]
👋 I've just released version 1.6.2 with these changes. Check out the release notes: https://github.com/cargo-lambda/cargo-lambda/releases/tag/v1.6.2
